# Generated by Django 5.1.4 on 2025-01-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0005_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='', max_length=150, unique=True, verbose_name='Nombre de usuario'),
        ),
    ]
